# -*- coding: utf-8 -*-
"""Adaptive_ROI_MobileNetV2_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14yFBXxgx1Zh11g-IyF3drbVJc9H6my50

# 🎯 Adaptive ROI-Driven Inference — MobileNetV2 Training Pipeline v2
**Paper:** *Adaptive ROI-Driven Inference for Low-Latency and Energy-Efficient Mobile Vision Systems*
**Dataset: COCO train2017** — 118,287 images, guaranteed 500+ crops per class

### Why COCO train2017 (not ImageNet mini)?
| Class | COCO train2017 instances | ImageNet-mini |
|---|---|---|
| person | ~262,465 | sparse |
| car | ~43,867 | sparse |
| cat | ~4,768 | sparse |
| dog | ~5,508 | sparse |
| bottle | ~24,342 | sparse |
| cell phone | ~6,434 | **only 17** |
| bicycle | ~7,113 | sparse |
| backpack | ~8,720 | sparse |

COCO train2017 has all 8 classes with **thousands** of annotated bounding boxes each — we crop those boxes to get clean, tightly-cropped object images exactly matching the ROI pipeline in the paper.

---
### Pipeline
1. Install deps → 2. Download COCO train2017 → 3. Crop 500 clean ROIs/class → 4. 70/15/15 split → 5. MobileNetV2 transfer learning → 6. Fine-tune → 7. Evaluate → 8. Prune 50% → 9. INT8 hybrid quantize → 10. Export `.tflite` + `labels.txt`

> ⚡ Set **Runtime → GPU (T4)** before running

---
## 📦 Step 1: Install Dependencies
"""

!pip install -q tensorflow==2.15.0
!pip install -q tensorflow-model-optimization
!pip install -q matplotlib seaborn scikit-learn tqdm Pillow opencv-python-headless

import tensorflow as tf
print('TensorFlow:', tf.__version__)
print('GPU:', tf.config.list_physical_devices('GPU'))

"""---
## 📥 Step 2: Download COCO train2017

This is ~18 GB. Colab's T4 instance has enough disk space. It takes ~10-15 minutes.

> **No Kaggle account needed** — we download directly from the official COCO servers.
"""

import os

# ── Download COCO train2017 images + annotations from official source ──────
print('Downloading COCO train2017 images (~18 GB)...')
print('This will take 10-20 minutes depending on Colab speed.')
!wget -q --show-progress http://images.cocodataset.org/zips/train2017.zip

print('\nDownloading COCO annotations...')
!wget -q --show-progress http://images.cocodataset.org/annotations/annotations_trainval2017.zip

print('\nUnzipping images...')
!unzip -q train2017.zip

print('Unzipping annotations...')
!unzip -q annotations_trainval2017.zip

print('\n✅ Done!')
!ls

"""---
## ✂️ Step 3: Crop 500 Clean ROI Images Per Class

This is the key step. We use COCO's bounding box annotations to **crop each object out** of the full image — exactly like how the Android app extracts ROIs at runtime. This gives the model training data that perfectly matches what it will see during inference.
"""

import json
import cv2
import numpy as np
import random
from PIL import Image
from tqdm import tqdm
import shutil

# ─── CONFIG (Paper Table I) ───────────────────────────────────────────────
TARGET_CLASSES   = ['person', 'bicycle', 'car', 'cat', 'dog',
                    'bottle', 'cell phone', 'backpack']
CLASS_FOLDER_MAP = {cls: cls.replace(' ', '_') for cls in TARGET_CLASSES}
FOLDER_NAMES     = list(CLASS_FOLDER_MAP.values())

IMAGES_PER_CLASS = 500   # exactly as stated in paper Table I
IMG_SIZE         = 224   # MobileNetV2 input
TRAIN_RATIO      = 0.70
VAL_RATIO        = 0.15
# TEST_RATIO = 0.15 (remainder)

MIN_CROP_PX  = 40    # minimum bounding box side length in pixels
MIN_AREA_PX  = 1600  # minimum bbox area (40x40)
SEED         = 42
random.seed(SEED)
np.random.seed(SEED)

OUTPUT_DIR = '/content/dataset'

# Clean any previous run
if os.path.exists(OUTPUT_DIR):
    shutil.rmtree(OUTPUT_DIR)

for split in ['train', 'val', 'test']:
    for folder in FOLDER_NAMES:
        os.makedirs(os.path.join(OUTPUT_DIR, split, folder), exist_ok=True)

print('✅ Output folder structure created')
print(f'Classes : {FOLDER_NAMES}')

# ─── Load COCO train2017 annotations ─────────────────────────────────────
ANNO_PATH = 'annotations/instances_train2017.json'
IMG_DIR   = 'train2017'

print('Loading COCO annotations (this JSON is ~250 MB, takes ~30s)...')
with open(ANNO_PATH) as f:
    coco = json.load(f)

# Build lookup dicts
image_id_to_info = {img['id']: img for img in coco['images']}
cat_id_to_name   = {cat['id']: cat['name'] for cat in coco['categories']}
cat_name_to_id   = {cat['name']: cat['id'] for cat in coco['categories']}

print(f'Total images      : {len(coco["images"]):,}')
print(f'Total annotations : {len(coco["annotations"]):,}')
print(f'Total categories  : {len(coco["categories"])}')

# Check our target classes exist
print('\nTarget class IDs in COCO:')
target_cat_ids = {}
for cls in TARGET_CLASSES:
    if cls in cat_name_to_id:
        cid = cat_name_to_id[cls]
        target_cat_ids[cid] = cls
        print(f'  [{cid:2d}] {cls}')
    else:
        print(f'  [??] {cls} — NOT FOUND in COCO!')

# ─── Group annotations by class ───────────────────────────────────────────
from collections import defaultdict

anns_by_class = defaultdict(list)
for ann in coco['annotations']:
    if ann['category_id'] in target_cat_ids:
        cls = target_cat_ids[ann['category_id']]
        x, y, w, h = ann['bbox']
        # Filter: must be large enough to be a meaningful crop
        if w >= MIN_CROP_PX and h >= MIN_CROP_PX and w * h >= MIN_AREA_PX:
            anns_by_class[cls].append(ann)

print('Annotations available (after size filter):')
for cls in TARGET_CLASSES:
    n = len(anns_by_class[cls])
    bar = '█' * min(50, n // 200)
    print(f'  {cls:12s}: {n:6,}  {bar}')

# ─── Crop & save 500 images per class with 70/15/15 split ────────────────
def crop_and_save(ann, image_info, img_dir, out_path, img_size=224):
    img_path = os.path.join(img_dir, image_info['file_name'])
    img = cv2.imread(img_path)
    if img is None:
        return False

    x, y, w, h = map(int, ann['bbox'])
    ih, iw = img.shape[:2]

    # Add small context padding (10%) around the bbox for better context
    pad_x = int(w * 0.10)
    pad_y = int(h * 0.10)
    x1 = max(0, x - pad_x)
    y1 = max(0, y - pad_y)
    x2 = min(iw, x + w + pad_x)
    y2 = min(ih, y + h + pad_y)

    crop = img[y1:y2, x1:x2]
    if crop.size == 0 or crop.shape[0] < 10 or crop.shape[1] < 10:
        return False

    crop = cv2.resize(crop, (img_size, img_size), interpolation=cv2.INTER_LANCZOS4)
    cv2.imwrite(out_path, crop, [cv2.IMWRITE_JPEG_QUALITY, 93])
    return True


total_saved = 0
final_counts = {split: {} for split in ['train', 'val', 'test']}

for cls in TARGET_CLASSES:
    folder = CLASS_FOLDER_MAP[cls]
    anns   = anns_by_class[cls].copy()
    random.shuffle(anns)

    saved = []
    for ann in tqdm(anns, desc=f'{cls:12s}', leave=False):
        if len(saved) >= IMAGES_PER_CLASS:
            break
        img_info = image_id_to_info[ann['image_id']]
        # Temp path — we'll move to split folders after
        tmp_path = f'/tmp/roi_{cls}_{len(saved)}.jpg'
        if crop_and_save(ann, img_info, IMG_DIR, tmp_path, IMG_SIZE):
            saved.append(tmp_path)

    # Shuffle and split into 70/15/15
    random.shuffle(saved)
    n = len(saved)
    n_train = int(n * TRAIN_RATIO)
    n_val   = int(n * VAL_RATIO)

    split_map = (
        ('train', saved[:n_train]),
        ('val',   saved[n_train:n_train + n_val]),
        ('test',  saved[n_train + n_val:]),
    )

    for split_name, paths in split_map:
        final_counts[split_name][folder] = 0
        for i, src in enumerate(paths):
            dst = os.path.join(OUTPUT_DIR, split_name, folder, f'{i:04d}.jpg')
            shutil.move(src, dst)
            final_counts[split_name][folder] += 1
            total_saved += 1

    print(f'  {cls:12s}: {n} saved  '
          f'(train={final_counts["train"][folder]}, '
          f'val={final_counts["val"][folder]}, '
          f'test={final_counts["test"][folder]})')

print(f'\n✅ Total images saved: {total_saved}')
print(f'   Train : {sum(final_counts["train"].values())}')
print(f'   Val   : {sum(final_counts["val"].values())}')
print(f'   Test  : {sum(final_counts["test"].values())}')

# ─── Visualise sample crops ────────────────────────────────────────────────
import matplotlib.pyplot as plt
import glob

fig, axes = plt.subplots(2, 8, figsize=(20, 6))
for col, folder in enumerate(FOLDER_NAMES):
    imgs = glob.glob(os.path.join(OUTPUT_DIR, 'train', folder, '*.jpg'))[:2]
    for row, img_path in enumerate(imgs):
        img = cv2.imread(img_path)[:,:,::-1]
        axes[row, col].imshow(img)
        axes[row, col].set_title(folder, fontsize=8)
        axes[row, col].axis('off')
plt.suptitle('Sample Training Crops from COCO train2017', fontsize=13)
plt.tight_layout()
plt.savefig('/content/sample_crops.png', dpi=120)
plt.show()
print('Sample crops shown ✅')

"""---
## 🔄 Step 4: Data Generators with Augmentation
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

BATCH_SIZE = 32

# MobileNetV2 preprocess_input scales RGB to [-1, 1]
preprocess = tf.keras.applications.mobilenet_v2.preprocess_input

train_datagen = ImageDataGenerator(
    preprocessing_function=preprocess,
    rotation_range=25,
    zoom_range=0.25,
    horizontal_flip=True,
    brightness_range=[0.4, 1.6],   # illumination robustness (paper Section III-E)
    width_shift_range=0.15,
    height_shift_range=0.15,
    shear_range=0.1,
    fill_mode='nearest'
)

eval_datagen = ImageDataGenerator(preprocessing_function=preprocess)

train_gen = train_datagen.flow_from_directory(
    os.path.join(OUTPUT_DIR, 'train'),
    target_size=(224, 224), batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=True, seed=SEED
)

val_gen = eval_datagen.flow_from_directory(
    os.path.join(OUTPUT_DIR, 'val'),
    target_size=(224, 224), batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=False
)

test_gen = eval_datagen.flow_from_directory(
    os.path.join(OUTPUT_DIR, 'test'),
    target_size=(224, 224), batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=False
)

NUM_CLASSES = train_gen.num_classes
CLASS_NAMES = list(train_gen.class_indices.keys())
print(f'Classes ({NUM_CLASSES}): {CLASS_NAMES}')
print(f'Train: {train_gen.n} | Val: {val_gen.n} | Test: {test_gen.n}')

"""---
## 🧠 Step 5: Build MobileNetV2 Model (Transfer Learning)
"""

# ── Phase 1: Freeze backbone, train only custom head ──────────────────────
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(224, 224, 3), include_top=False, weights='imagenet'
)
base_model.trainable = False

inputs  = tf.keras.Input(shape=(224, 224, 3))
x = base_model(inputs, training=False)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dense(256, activation='relu',
    kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.Dense(128, activation='relu',
    kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
x = tf.keras.layers.Dropout(0.3)(x)
outputs = tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')(x)

model = tf.keras.Model(inputs, outputs, name='adaptive_roi_mobilenetv2')

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-3),
    loss='categorical_crossentropy',
    metrics=['accuracy',
             tf.keras.metrics.TopKCategoricalAccuracy(k=3, name='top3_acc')]
)

print(f'Total params     : {model.count_params():,}')
print(f'Trainable params : {sum(tf.size(w).numpy() for w in model.trainable_weights):,}')

"""---
## 🚀 Step 6: Phase 1 — Train Head Only (10 epochs)
"""

cb1 = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_accuracy', patience=4, restore_best_weights=True, verbose=1),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss', factor=0.5, patience=2, min_lr=1e-6, verbose=1),
    tf.keras.callbacks.ModelCheckpoint(
        '/content/best_phase1.keras', monitor='val_accuracy',
        save_best_only=True, verbose=0)
]

history1 = model.fit(
    train_gen, validation_data=val_gen,
    epochs=10, callbacks=cb1, verbose=1
)
print(f'\nPhase 1 best val_accuracy: {max(history1.history["val_accuracy"]):.4f}')

"""---
## 🔥 Step 7: Phase 2 — Fine-Tune Top 30 Base Layers
"""

base_model.trainable = True
for layer in base_model.layers[:-30]:
    layer.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-4),
    loss='categorical_crossentropy',
    metrics=['accuracy',
             tf.keras.metrics.TopKCategoricalAccuracy(k=3, name='top3_acc')]
)

cb2 = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_accuracy', patience=5, restore_best_weights=True, verbose=1),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss', factor=0.3, patience=3, min_lr=1e-7, verbose=1),
    tf.keras.callbacks.ModelCheckpoint(
        '/content/best_model.keras', monitor='val_accuracy',
        save_best_only=True, verbose=1)
]

history2 = model.fit(
    train_gen, validation_data=val_gen,
    epochs=15, callbacks=cb2, verbose=1
)
print(f'\nPhase 2 best val_accuracy: {max(history2.history["val_accuracy"]):.4f}')

"""---
## 📊 Step 8: Training Curves
"""

import matplotlib.pyplot as plt

def merge(h1, h2):
    return {k: h1.history[k] + h2.history[k] for k in h1.history}

hist = merge(history1, history2)
p1   = len(history1.history['accuracy'])
ep   = range(1, len(hist['accuracy']) + 1)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
for ax, (trk, vlk, title) in zip(axes, [
    ('accuracy',  'val_accuracy',  'Accuracy'),
    ('loss',      'val_loss',      'Loss'),
    ('top3_acc',  'val_top3_acc',  'Top-3 Accuracy'),
]):
    ax.plot(ep, hist[trk], 'b-o', markersize=3, label='Train')
    ax.plot(ep, hist[vlk], 'r-o', markersize=3, label='Val')
    ax.axvline(p1, color='gray', ls='--', label='Phase 2 start')
    if 'acc' in trk:
        ax.axhline(0.875, color='green', ls=':', label='Target 87.5%')
    ax.set_title(title); ax.set_xlabel('Epoch')
    ax.legend(); ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('/content/training_curves.png', dpi=150)
plt.show()

"""---
## ✅ Step 9: Test Set Evaluation + Confusion Matrix
"""

import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

model = tf.keras.models.load_model('/content/best_model.keras')
test_loss, test_acc, test_top3 = model.evaluate(test_gen, verbose=1)
print(f'\nTest Accuracy : {test_acc*100:.2f}%')
print(f'Test Top-3    : {test_top3*100:.2f}%')

test_gen.reset()
y_pred = np.argmax(model.predict(test_gen, verbose=1), axis=1)
y_true = test_gen.classes

print('\nClassification Report:')
print(classification_report(y_true, y_pred, target_names=CLASS_NAMES))

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES)
plt.title('Confusion Matrix — Test Set')
plt.ylabel('True'); plt.xlabel('Predicted')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('/content/confusion_matrix.png', dpi=150)
plt.show()

"""---
## ✂️ Step 10: Structured Pruning — 50% Sparsity

Paper Section III-J: *"Structured pruning of 50% applied for balanced accuracy"*  
Paper Table II target: ~1.2 M params, ~2.66 MB model size

---
## Step 11: Hybrid Quantization → TFLite
Paper Table II: INT8 weights → ~2.66 MB, ~10-25 ms latency

---
## 🧪 Step 12: TFLite Accuracy + Latency Benchmark
---
## 🏷️ Step 13: Generate labels.txt for Android

---
## 💾 Step 14: Download All Files

### Files to copy into Android Studio:
```
app/src/main/assets/
    ├── model.tflite       ← main model (hybrid quantized)
    └── labels.txt         ← class names in output order
```
"""

# ============================================================
# FIXED Steps 10–16: Pruning + Quantization + Download
# Tested logic for TF 2.20 + Python 3.12
# ============================================================

import numpy as np
import os, time, glob
import tensorflow as tf

print(f"TF version: {tf.__version__}")

# ════════════════════════════════════════════════════════════
# STEP 10: Manual Magnitude Pruning (50% sparsity on Dense layers)
# ════════════════════════════════════════════════════════════
print("\n" + "="*55)
print("STEP 10: 50% Magnitude Pruning on Dense Layers")
print("="*55)

def apply_magnitude_pruning(model, target_sparsity=0.50):
    # Clone the model so we don't modify the trained original
    model_copy = tf.keras.models.clone_model(model)
    model_copy.set_weights(model.get_weights())

    total_pruned = 0
    total_weights = 0

    for layer in model_copy.layers:
        if not isinstance(layer, tf.keras.layers.Dense):
            continue
        weights = layer.get_weights()   # [kernel, bias]
        kernel  = weights[0]

        flat      = np.abs(kernel.flatten())
        k         = int(len(flat) * target_sparsity)
        if k == 0:
            continue
        # Find the k-th smallest absolute value as threshold
        threshold = np.partition(flat, k)[k]
        mask      = np.abs(kernel) >= threshold
        weights[0] = kernel * mask
        layer.set_weights(weights)

        pruned = int(np.sum(mask == 0))
        total_pruned  += pruned
        total_weights += kernel.size
        print(f"  {layer.name:30s}: {pruned:6d}/{kernel.size:6d} zeroed "
              f"({pruned/kernel.size*100:.1f}%)")

    # Overall sparsity across all layers
    az = at = 0
    for layer in model_copy.layers:
        for w in layer.weights:
            a = w.numpy()
            az += int(np.sum(a == 0))
            at += a.size
    print(f"\n  Dense-layer sparsity : {total_pruned/max(total_weights,1)*100:.1f}%  (paper target: 50%)")
    print(f"  Overall sparsity     : {az/at*100:.1f}%")
    return model_copy

model_pruned = apply_magnitude_pruning(model, target_sparsity=0.50)

# Fine-tune 3 epochs to recover accuracy after pruning
print("\nFine-tuning pruned model for 3 epochs...")
model_pruned.compile(
    optimizer=tf.keras.optimizers.Adam(1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

cb_ft = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_accuracy', patience=2,
        restore_best_weights=True, verbose=1
    ),
    tf.keras.callbacks.ModelCheckpoint(
        '/content/model_pruned.keras',
        monitor='val_accuracy', save_best_only=True, verbose=0
    )
]

model_pruned.fit(
    train_gen, validation_data=val_gen,
    epochs=3, callbacks=cb_ft, verbose=1
)

# Reload best checkpoint
model_pruned = tf.keras.models.load_model('/content/model_pruned.keras')
model_pruned.compile(
    optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy']
)

_, acc_pruned = model_pruned.evaluate(test_gen, verbose=0)
print(f"\nPruned model test accuracy : {acc_pruned*100:.2f}%")
print(f"Accuracy drop from pruning : {(test_acc - acc_pruned)*100:.2f}%  (paper target ≤2.4%)")


# ════════════════════════════════════════════════════════════
# STEP 11: Hybrid Quantization → TFLite
# FIX 1: removed verbose=0 from flow_from_directory (removed in TF 2.20)
# FIX 2: use os.listdir-based generator instead of ImageDataGenerator
#         for calibration — avoids ALL flow_from_directory issues
# FIX 3: removed SELECT_TF_OPS (caused calibration TypeError)
# ════════════════════════════════════════════════════════════
print("\n" + "="*55)
print("STEP 11: INT8 Hybrid Quantization → TFLite")
print("="*55)

# Collect validation image paths once (plain file list — no Keras generator)
val_img_paths = sorted(
    glob.glob(os.path.join(OUTPUT_DIR, 'val', '*', '*.jpg'))
)
print(f"Calibration images available: {len(val_img_paths)}")

# Shuffle and cap at 200 for calibration speed
import random
random.shuffle(val_img_paths)
calib_paths = val_img_paths[:200]

def representative_dataset_gen():
    """
    Pure-NumPy calibration generator.
    Reads each image from disk, resizes to 224x224,
    applies MobileNetV2 preprocess_input (scale to [-1,1]),
    yields shape (1, 224, 224, 3) float32.
    No Keras generators — zero API compatibility issues.
    """
    preprocess = tf.keras.applications.mobilenet_v2.preprocess_input
    for img_path in calib_paths:
        try:
            img = tf.io.read_file(img_path)
            img = tf.image.decode_jpeg(img, channels=3)
            img = tf.image.resize(img, [224, 224])
            img = tf.cast(img, tf.float32)
            img = preprocess(img)                       # → [-1, 1]
            img = tf.expand_dims(img, axis=0)           # → (1, 224, 224, 3)
            yield [img.numpy()]
        except Exception:
            continue   # skip corrupt images silently


# ── Convert A: Hybrid TFLite (INT8 weights + FP32 activations) ──────────────
print("\nConverting → Hybrid TFLite (INT8 weights, FP32 activations)...")
converter_hybrid = tf.lite.TFLiteConverter.from_keras_model(model_pruned)
converter_hybrid.optimizations           = [tf.lite.Optimize.DEFAULT]
# NOTE: Do NOT add SELECT_TF_OPS here — it breaks calibration in TF 2.20
converter_hybrid.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]
converter_hybrid.representative_dataset = representative_dataset_gen

tflite_hybrid = converter_hybrid.convert()

with open('/content/model.tflite', 'wb') as f:
    f.write(tflite_hybrid)

size_hybrid = os.path.getsize('/content/model.tflite') / 1e6
print(f"✅ model.tflite saved  —  {size_hybrid:.2f} MB  (paper target: ~2.66 MB)")


# ── Convert B: Full INT8 TFLite (max speed on NNAPI devices) ────────────────
print("\nConverting → Full INT8 TFLite...")
try:
    converter_int8 = tf.lite.TFLiteConverter.from_keras_model(model_pruned)
    converter_int8.optimizations              = [tf.lite.Optimize.DEFAULT]
    converter_int8.target_spec.supported_ops  = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter_int8.inference_input_type       = tf.float32   # keep float I/O for CameraX
    converter_int8.inference_output_type      = tf.float32
    converter_int8.representative_dataset     = representative_dataset_gen

    tflite_int8 = converter_int8.convert()
    with open('/content/model_int8.tflite', 'wb') as f:
        f.write(tflite_int8)
    size_int8 = os.path.getsize('/content/model_int8.tflite') / 1e6
    print(f"✅ model_int8.tflite saved  —  {size_int8:.2f} MB")
except Exception as e:
    print(f"Full INT8 skipped: {e}")
    print("   → model.tflite (hybrid) is sufficient for Android")
    size_int8 = 0.0


# ════════════════════════════════════════════════════════════
# STEP 12: Benchmark TFLite — accuracy + latency
# ════════════════════════════════════════════════════════════
print("\n" + "="*55)
print("STEP 12: TFLite Benchmark")
print("="*55)

def benchmark_tflite(model_path, data_gen, n_batches=10):
    interp = tf.lite.Interpreter(model_path=model_path)
    interp.allocate_tensors()
    inp_idx = interp.get_input_details()[0]['index']
    out_idx = interp.get_output_details()[0]['index']

    data_gen.reset()
    correct = total = 0
    latencies = []

    for i, (imgs, labels) in enumerate(data_gen):
        if i >= n_batches:
            break
        for j in range(len(imgs)):
            x = np.expand_dims(imgs[j], 0).astype(np.float32)
            interp.set_tensor(inp_idx, x)
            t0 = time.perf_counter()
            interp.invoke()
            latencies.append((time.perf_counter() - t0) * 1000)
            pred = np.argmax(interp.get_tensor(out_idx)[0])
            if pred == np.argmax(labels[j]):
                correct += 1
            total += 1

    acc     = correct / total if total > 0 else 0.0
    avg_lat = float(np.mean(latencies)) if latencies else 0.0
    return acc, avg_lat

acc_h, lat_h = benchmark_tflite('/content/model.tflite', test_gen, n_batches=10)
print(f"\n  Hybrid TFLite  → Accuracy: {acc_h*100:.2f}%   Avg latency: {lat_h:.1f} ms")
print(f"  Accuracy drop vs original: {(test_acc - acc_h)*100:.2f}%  (paper target ≤3–4%)")


# ════════════════════════════════════════════════════════════
# STEP 13: Verify TFLite tensor shapes
# ════════════════════════════════════════════════════════════
print("\n" + "="*55)
print("STEP 13: TFLite Tensor Verification")
print("="*55)

interp = tf.lite.Interpreter(model_path='/content/model.tflite')
interp.allocate_tensors()
inp_det = interp.get_input_details()[0]
out_det = interp.get_output_details()[0]

print(f"  Input  shape : {inp_det['shape']}   dtype: {inp_det['dtype']}")
print(f"  Output shape : {out_det['shape']}  dtype: {out_det['dtype']}")
print(f"  Expected     : input=(1,224,224,3)  output=(1,{NUM_CLASSES})")

# Sanity check with random noise
dummy = np.random.randn(1, 224, 224, 3).astype(np.float32)
interp.set_tensor(inp_det['index'], dummy)
interp.invoke()
result = interp.get_tensor(out_det['index'])[0]
print(f"\n  Prob sum (must be ~1.0): {result.sum():.4f}")
print(f"  Output probabilities (random noise — values should be spread):")
for i, (name, prob) in enumerate(zip(CLASS_NAMES, result)):
    bar = '█' * int(prob * 30)
    print(f"    [{i}] {name:12s}: {prob:.4f}  {bar}")


# ════════════════════════════════════════════════════════════
# STEP 14: Generate labels.txt for Android
# ════════════════════════════════════════════════════════════
print("\n" + "="*55)
print("STEP 14: labels.txt for Android")
print("="*55)

sorted_labels = [k for k, v in sorted(
    train_gen.class_indices.items(), key=lambda x: x[1]
)]

with open('/content/labels.txt', 'w') as f:
    for label in sorted_labels:
        f.write(label + '\n')

print("labels.txt content (copy to app/src/main/assets/):")
for i, lbl in enumerate(sorted_labels):
    print(f"  [{i}] {lbl}")


# ════════════════════════════════════════════════════════════
# STEP 15: Final Summary Table
# ════════════════════════════════════════════════════════════
print("\n" + "="*55)
print("FINAL SUMMARY")
print("="*55)
print(f"  {'Model':<40} {'Accuracy':>10}  {'Size':>10}")
print(f"  {'-'*62}")
print(f"  {'Original MobileNetV2 (paper baseline)':<40} {test_acc*100:>9.1f}%  {'9.26 MB':>10}")
print(f"  {'Pruned 50% (Keras)':<40} {acc_pruned*100:>9.1f}%  {'—':>10}")
print(f"  {'Pruned + Hybrid TFLite  ← model.tflite':<40} {acc_h*100:>9.1f}%  {size_hybrid:>9.2f}MB")
if size_int8 > 0:
    acc_i, _ = benchmark_tflite('/content/model_int8.tflite', test_gen, 5)
    print(f"  {'Pruned + Full INT8      ← model_int8.tflite':<40} {acc_i*100:>9.1f}%  {size_int8:>9.2f}MB")
print(f"\n  Accuracy drop (hybrid vs original) : {(test_acc - acc_h)*100:.1f}%")
print(f"\n  ✅ Files ready for Android Studio:")
print(f"     /content/model.tflite  → app/src/main/assets/model.tflite")
print(f"     /content/labels.txt    → app/src/main/assets/labels.txt")


# ════════════════════════════════════════════════════════════
# STEP 16: Download
# ════════════════════════════════════════════════════════════
print("\n" + "="*55)
print("STEP 16: Downloading Files")
print("="*55)

# Verify files exist before downloading
for fname in ['model.tflite', 'labels.txt', 'model_int8.tflite']:
    fpath = f'/content/{fname}'
    if os.path.exists(fpath):
        print(f"  ✅ {fname:30s}  {os.path.getsize(fpath)/1e3:.1f} KB")
    else:
        print(f"  ⚠️  {fname} not found — skipping")

from google.colab import files
files.download('/content/model.tflite')
files.download('/content/labels.txt')
if os.path.exists('/content/model_int8.tflite'):
    files.download('/content/model_int8.tflite')

print("\n✅ All downloads started!")

"""---
## 📱 Android Integration — Quick Reference

### 1. Kotlin preprocessing (matches MobileNetV2 preprocess_input)
```kotlin
fun preprocessRoi(roi: Bitmap): ByteBuffer {
    val resized = Bitmap.createScaledBitmap(roi, 224, 224, true)
    val buf = ByteBuffer.allocateDirect(4 * 224 * 224 * 3).apply {
        order(ByteOrder.nativeOrder())
    }
    for (y in 0 until 224) for (x in 0 until 224) {
        val px = resized.getPixel(x, y)
        // MobileNetV2 preprocess: scale [0,255] → [-1,1]
        buf.putFloat(((px shr 16 and 0xFF) / 127.5f) - 1f)  // R
        buf.putFloat(((px shr  8 and 0xFF) / 127.5f) - 1f)  // G
        buf.putFloat(((px       and 0xFF) / 127.5f) - 1f)  // B
    }
    return buf
}
```

### 2. Run inference on ROI
```kotlin
fun classify(roi: Bitmap): Pair<String, Float> {
    val out = Array(1) { FloatArray(8) }          // 8 classes
    tflite.run(preprocessRoi(roi), out)
    val idx = out[0].indices.maxByOrNull { out[0][it] }!!
    return Pair(labels[idx], out[0][idx])          // label, confidence
}
```

### 3. Confidence threshold γ (paper Eq.17 — only draw bbox if confident)
```kotlin
val (label, confidence) = classify(roiBitmap)
if (confidence >= 0.60f) {
    drawBoundingBox(canvas, roiRect, label, confidence)
    logEvent(roiBitmap, label, System.currentTimeMillis())
}
```

### 4. Class output order from labels.txt
```
[0] backpack
[1] bicycle  
[2] bottle
[3] car
[4] cat
[5] cell_phone
[6] dog
[7] person
```
*(always use the downloaded labels.txt — alphabetical order)*
"""